# Python Numpy Practice

In [2]:
import numpy as np 

In [21]:
# making a numpy array
myarr = np.array([[1,2,36,25]])

In [4]:
myarr

array([ 1,  2, 36, 25])

In [5]:
# we can also define the data types
myarr1 = np.array([1,65,98,596,58], np.int32)

In [6]:
myarr1.dtype

dtype('int32')

In [7]:
myarr[3]

25

In [23]:
myarr.shape

(1, 4)

In [25]:
myarr[0,1] = 45

In [27]:
myarr

array([[ 1, 45, 36, 25]])

# There are 6 general mechanisms for creating arrays:
**1. 
Conversion from other Python structures (i.e. lists and tuple**s)

In [31]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [33]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
listarray.dtype

dtype('int32')

In [37]:
listarray.shape

(3, 3)

In [39]:
listarray.size

9

In [41]:
listarray = np.array([{1,23,56}])

In [43]:
listarray

array([{56, 1, 23}], dtype=object)

**2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [46]:
zeros = np.zeros((2,5))

In [48]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
zeros.dtype

dtype('float64')

In [52]:
zeros.size

10

In [54]:
zeros.shape

(2, 5)

In [56]:
range = np.arange(15)

In [58]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
# returns equallys spaced elements
linspace = np.linspace(1,50,10)

In [62]:
linspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [64]:
emp = np.empty((2,3))

In [66]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29060871e-306, 1.89146896e-307, 7.56571288e-307]])

In [68]:
emp_like = np.empty_like(linspace)

In [70]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [72]:
ide = np.identity(5)

In [74]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
ide.shape

(5, 5)

In [78]:
arr = np.arange(99)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [82]:
arr = arr.reshape(3,33)

In [84]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [86]:
# it will make your array straight (1D Array)
arr = arr.ravel()

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [90]:
arr.shape

(99,)

In [92]:
ones = np.ones(5)

In [94]:
ones

array([1., 1., 1., 1., 1.])

In [96]:
ones.shape

(5,)

In [98]:
ones.dtype

dtype('float64')

# Axis in Numpy:

In [103]:
arr2  = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [105]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
# axis=0 works on rows in downward manner
arr2.sum(axis=0)

array([12, 15, 18])

In [109]:
# axis=1 works on column in rightside manner
arr2.sum(axis=1)

array([ 6, 15, 24])

In [113]:
# for transpose
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [115]:
arr2.flat

In [123]:
for item in arr2.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [125]:
# ndim returns the number of dimensions in the array
arr2.ndim

2

In [127]:
arr2.size

9

In [129]:
# return the no of bytes our array is consuming
arr2.nbytes

36

In [131]:
one = np.array([1,21,56,41])

In [133]:
# return the index of the max element present in the array
one.argmax()

2

In [135]:
# return the index of the min element present in the array
one.argmin()

0

In [137]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [139]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr2.argmin()

0

In [143]:
arr2.argmax()

8

In [145]:
arr2.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [147]:
arr2.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [149]:
arr2.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [151]:
arr2.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [153]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
arr2.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
arr3 = np.array([[5, 2, 0],
       [4, 5, 1],
       [2, 2, 4]])

In [169]:
arr2 + arr3

array([[ 6,  4,  3],
       [ 8, 10,  7],
       [ 9, 10, 13]])

In [173]:
# we can not do these operation using list, that's why numpy gives us the facility to do these type of operations using array
# for example!
[321, 45] + [23, 569]
# it extends the list 

[321, 45, 23, 569]

In [175]:
arr2 * arr3

array([[ 5,  4,  0],
       [16, 25,  6],
       [14, 16, 36]])

In [179]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [181]:
arr2.sum()

45

In [185]:
arr2.max()

9

In [187]:
arr2.min()

1

In [189]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
np.where(arr2 > 5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [193]:
type(np.where(arr2 > 5))

tuple

In [195]:
np.count_nonzero(arr2)

9

In [199]:
np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# Let's Check that how Numpy takes minimum size / location in the memory

In [202]:
import sys

In [204]:
py_array = [1,2,3,4]

In [206]:
numpy_array = np.array(py_array)

In [208]:
sys.getsizeof(1) * len(py_array)

112

In [210]:
numpy_array.itemsize * numpy_array.size

16